export const ADD_COMMENT = 'ADD_COMMENT';
export const BLOGS_LOADING = 'BLOGS_LOADING';
export const BLOGS_FAILED = 'BLOGS_FAILED';
export const ADD_BLOGS = 'ADD_BLOGS';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';